<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Shipping cost, delivery date, and ord_9d508e</name>
   <tag></tag>
   <elementGuidId>208c3aa6-dee2-47de-9e69-24acb8f79c2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buy-now-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='buy-now-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f17e3d0f-ebe9-4ad5-8969-09ee3d776474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buy-now-button</value>
      <webElementGuid>60f9e55a-0619-4cd2-ba0c-6f05ce9f9410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.buy-now</value>
      <webElementGuid>37ceb1d0-f6e2-42d1-aaaf-789d0c419f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Buy Now</value>
      <webElementGuid>b064c9d1-084c-47ff-becf-c8a8b4686229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover</name>
      <type>Main</type>
      <value>Select &lt;b>__dims__</value>
      <webElementGuid>d35b0855-21d3-4321-8681-464679898238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>b6c436b4-ba28-4fa7-9de3-00bcdd2e6b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4a3582eb-ec3c-48cc-bc76-20bec9f2f045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>submit.buy-now-announce</value>
      <webElementGuid>32ae45bd-a971-440f-ba5c-8da27811ae38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buy-now-button&quot;)</value>
      <webElementGuid>223fea21-089d-415f-98e3-deeed3cf46a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='buy-now-button']</value>
      <webElementGuid>0ee2c08e-a8d8-4fb1-996d-df8e152a1f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='submit.buy-now']/span/input</value>
      <webElementGuid>bcff1b2c-7f07-49f7-a958-161c0c11e28f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/input</value>
      <webElementGuid>2913edd3-1461-4cdb-8dc3-e9a4a5f2715c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'buy-now-button' and @name = 'submit.buy-now' and @title = 'Buy Now' and @type = 'submit']</value>
      <webElementGuid>452ecdee-7441-42db-b8e4-553705e275ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
