<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_s-image</name>
   <tag></tag>
   <elementGuidId>cc1e4eca-d5e5-4d09-bf25-2727c76b0016</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.s-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search']/div/div/div/span/div/div[2]/div/div/span/div/div/div/div/div/div[2]/div/span/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0b7a36d8-f6d2-40c7-b4fa-21c1a48f8bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s-image</value>
      <webElementGuid>a355f2bc-d111-4cf7-bb1b-8f5d5200bb2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/71xH0ALI4-L._AC_UY218_.jpg</value>
      <webElementGuid>d024c97c-1e5e-4893-a3e0-fb096fbceedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/71xH0ALI4-L._AC_UY218_.jpg 1x, https://m.media-amazon.com/images/I/71xH0ALI4-L._AC_UY327_FMwebp_QL65_.jpg 1.5x, https://m.media-amazon.com/images/I/71xH0ALI4-L._AC_UY436_FMwebp_QL65_.jpg 2x, https://m.media-amazon.com/images/I/71xH0ALI4-L._AC_UY545_FMwebp_QL65_.jpg 2.5x, https://m.media-amazon.com/images/I/71xH0ALI4-L._AC_UY654_FMwebp_QL65_.jpg 3x</value>
      <webElementGuid>37729d7a-6d15-4ed2-95c8-cafc1e9b9a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Ikigai: The Japanese Secret to a Long and Happy Life</value>
      <webElementGuid>d8e2004a-6153-41ac-9676-217734092bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5e50b70e-ab66-4eba-b7e1-d8fd1ff7af99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-latency</name>
      <type>Main</type>
      <value>s-product-image</value>
      <webElementGuid>917d49af-b32e-4e8b-80b0-8384d79f620a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-source-density</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bee1a53a-748f-4863-ae04-ce1fc5532c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search&quot;)/div[@class=&quot;s-desktop-width-max s-desktop-content s-opposite-dir s-wide-grid-style sg-row&quot;]/div[@class=&quot;sg-col-20-of-24 s-matching-dir sg-col-16-of-20 sg-col sg-col-8-of-12 sg-col-12-of-16&quot;]/div[@class=&quot;sg-col-inner&quot;]/span[@class=&quot;rush-component s-latency-cf-section&quot;]/div[@class=&quot;s-main-slot s-result-list s-search-results sg-row&quot;]/div[@class=&quot;sg-col-20-of-24 s-result-item s-asin sg-col-0-of-12 sg-col-16-of-20 sg-col s-widget-spacing-small sg-col-12-of-16&quot;]/div[@class=&quot;sg-col-inner&quot;]/div[@class=&quot;s-widget-container s-spacing-small s-widget-container-height-small celwidget slot=MAIN template=SEARCH_RESULTS widgetId=search-results_1&quot;]/span[@class=&quot;a-declarative&quot;]/div[@class=&quot;puis-card-container s-card-container s-overflow-hidden aok-relative puis-include-content-margin puis puis-v2rh3j15wdcp4q29xeaptoa72x6 s-latency-cf-section puis-card-border&quot;]/div[@class=&quot;a-section&quot;]/div[@class=&quot;puisg-row&quot;]/div[@class=&quot;puisg-col puisg-col-4-of-12 puisg-col-4-of-16 puisg-col-4-of-20 puisg-col-4-of-24 puis-list-col-left&quot;]/div[@class=&quot;puisg-col-inner&quot;]/div[@class=&quot;s-product-image-container aok-relative s-text-center s-image-overlay-grey puis-image-overlay-grey s-padding-left-small s-padding-right-small puis-flex-expand-height puis puis-v2rh3j15wdcp4q29xeaptoa72x6&quot;]/div[@class=&quot;aok-relative&quot;]/span[@class=&quot;rush-component&quot;]/a[@class=&quot;a-link-normal s-no-outline&quot;]/div[@class=&quot;a-section aok-relative s-image-fixed-height&quot;]/img[@class=&quot;s-image&quot;]</value>
      <webElementGuid>df174328-ce72-488e-90d6-aae2a21e6de8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search']/div/div/div/span/div/div[2]/div/div/span/div/div/div/div/div/div[2]/div/span/a/div/img</value>
      <webElementGuid>76970c6b-89c7-4219-8bae-9a96d075c3b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Ikigai: The Japanese Secret to a Long and Happy Life']</value>
      <webElementGuid>859532e7-a244-4a32-a7b7-7b1b69e06b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/img</value>
      <webElementGuid>bc58efba-ea29-4841-b8b8-ab786c7a96b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://m.media-amazon.com/images/I/71xH0ALI4-L._AC_UY218_.jpg' and @alt = 'Ikigai: The Japanese Secret to a Long and Happy Life']</value>
      <webElementGuid>08b1c347-3a5e-44bf-a8d5-ead0070ff137</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
