<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_g0DVH8BGIhxENIQcoE49</name>
   <tag></tag>
   <elementGuidId>2f8fe8c3-675a-4d86-9264-e94efc57c737</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.g0DVH8BGIhxENIQcoE49</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='navbarMusicLogo']/img[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b5c1d771-0414-40ba-9a22-d8ef8580da4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>g0DVH8BGIhxENIQcoE49</value>
      <webElementGuid>128b9bc7-21b5-4e0a-92d9-85a4559cb890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d5fx445wy2wpk.cloudfront.net/static/logo.svg</value>
      <webElementGuid>a3213635-8ece-4e4d-afb8-9307498b6bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Amazon Music</value>
      <webElementGuid>de3f8f62-4653-4bd5-9ec1-8d1f7cd6fccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarMusicLogo&quot;)/img[@class=&quot;g0DVH8BGIhxENIQcoE49&quot;]</value>
      <webElementGuid>e3702ba6-9047-41de-b5ff-0f37e05bb1b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='navbarMusicLogo']/img[2]</value>
      <webElementGuid>717aa74c-913b-4197-826c-2e36e1934f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Amazon Music'])[2]</value>
      <webElementGuid>6a104c4e-30ae-4fff-8915-9fdd063c1dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>798ff80c-d866-4d26-b8f9-f7e08a413ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d5fx445wy2wpk.cloudfront.net/static/logo.svg' and @alt = 'Amazon Music']</value>
      <webElementGuid>5d4774ee-1e2a-4166-815a-3e24409f0a4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
