<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_mobile phones</name>
   <tag></tag>
   <elementGuidId>05bf76b7-716a-4436-b961-cfa9e63ad7ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.s-suggestion.s-suggestion-ellipsis-direction</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-flyout-searchAjax']/div[2]/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>895fbfe1-f7b6-408a-8e5a-f1a2e98a4611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s-suggestion s-suggestion-ellipsis-direction</value>
      <webElementGuid>a85fb0fc-8801-4e03-99ab-d57bb91756d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e65f7b73-cf2c-456e-8077-94ee0bb2f5d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>mobile phones</value>
      <webElementGuid>58535329-73b5-4632-b066-c15fda00b7cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mobile phones</value>
      <webElementGuid>bf5ed555-237c-4184-b6fa-29ead8b4d5aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-flyout-searchAjax&quot;)/div[@class=&quot;autocomplete-results-container&quot;]/div[@class=&quot;two-pane-results-container&quot;]/div[@class=&quot;left-pane-results-container&quot;]/div[1]/div[@class=&quot;s-suggestion-container&quot;]/div[@class=&quot;s-suggestion s-suggestion-ellipsis-direction&quot;]</value>
      <webElementGuid>dabd8f0b-4e04-4933-ad00-ea0f9b9d9c39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-flyout-searchAjax']/div[2]/div/div/div/div/div</value>
      <webElementGuid>6b68ac4c-0ce7-4891-a74e-580cc3be8753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>7d038881-6627-4bcc-a336-07958993f920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'mobile phones' or . = 'mobile phones')]</value>
      <webElementGuid>ad5181f0-49a1-4c36-ab30-7da0c0e4bac7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
