<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Amazon MusicStream millionsof songs</name>
   <tag></tag>
   <elementGuidId>5d0212a7-dd7e-4acf-bbb3-1a731846e02d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.navFooterDescItem > a.nav_a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navFooter']/div[4]/table/tbody/tr/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8c1bed08-c647-4937-b81b-b2da51993fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://music.amazon.com?ref=dm_aff_amz_com</value>
      <webElementGuid>3ac47f0c-36c1-40ed-88ae-69be5f9137bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav_a</value>
      <webElementGuid>d2ba5db0-cb5f-497e-9ce7-1a91417a60d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Amazon MusicStream millionsof songs</value>
      <webElementGuid>c700a932-26a4-409e-b237-b26f3444d0bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navFooter&quot;)/div[@class=&quot;navFooterLine navFooterLinkLine navFooterDescLine&quot;]/table[@class=&quot;navFooterMoreOnAmazon&quot;]/tbody[1]/tr[1]/td[@class=&quot;navFooterDescItem&quot;]/a[@class=&quot;nav_a&quot;]</value>
      <webElementGuid>61b2e881-f90f-4ade-8a4d-1b9dfaf0df6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navFooter']/div[4]/table/tbody/tr/td/a</value>
      <webElementGuid>d383d171-e85b-422d-b743-a828d15cbf28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://music.amazon.com?ref=dm_aff_amz_com')]</value>
      <webElementGuid>1b545803-ef4c-4d67-9b69-96621d76d586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>9930cb73-9de4-4bf0-b96a-1422ca0a4ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://music.amazon.com?ref=dm_aff_amz_com' and (text() = 'Amazon MusicStream millionsof songs' or . = 'Amazon MusicStream millionsof songs')]</value>
      <webElementGuid>2f56746b-8450-459a-b0c1-8907b1dde0b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
